recipeData:
  chartVersion: 9.0.5
  target_cluster: dev
  catalog_name: HPEEE
  catalog_description: Platform
  release_date: '2026-06-08'
  catalog_status: GA
  maintainer: HPE Devops
  values_file: hi.yaml
  recipes:
  - version: 1.4.0
    description: Major feature and stability update
    release_date: '2026-06-04'
    status: GA
    release_notes: Upgraded all core platform services to latest supported versions
    components:
      analytics-engine:
        version: 1.2.1
        release_date: '2026-06-03'
        upgrade_from:
        - 1.1.1
        upgrade_to:
        - 1.3.1
      postgres-db:
        version: 1.2.3
        release_date: '2026-06-03'
        upgrade_from:
        - 1.1.3
        upgrade_to:
        - 1.4.1
      stream-processor:
        version: 1.2.2
        release_date: '2026-06-03'
        upgrade_from:
        - 1.1.2
        upgrade_to:
        - 1.3.2
        - 1.4.2
      airflow:
        version: 1.3.3
        release_date: '2026-06-08'
        upgrade_from:
        - 1.3.2
        upgrade_to:
        - 1.3.3
    upgrade_to:
    - 1.4.1
    upgrade_from:
    - 1.3.9
